# Generated by Django 4.2.2 on 2023-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custom_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upassword', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255, unique=True)),
                ('isldap', models.SmallIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('work_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('person_id', models.IntegerField(null=True)),
                ('current_loc', models.IntegerField(null=True)),
                ('last_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('ubis_id', models.IntegerField(null=True)),
                ('sub_ubis_id', models.IntegerField(null=True)),
                ('jabatan', models.CharField(blank=True, max_length=200, null=True)),
                ('fixed_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=100, null=True)),
                ('main_role', models.CharField(max_length=11, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.CharField(blank=True, max_length=225, null=True)),
                ('app', models.CharField(blank=True, max_length=20, null=True)),
                ('is_telkom', models.SmallIntegerField(blank=True, null=True)),
                ('employment_category', models.CharField(blank=True, max_length=100, null=True)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('umur', models.IntegerField(null=True)),
                ('masa_bakti', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_id', models.SmallIntegerField(blank=True, null=True)),
                ('pendidikan', models.SmallIntegerField(blank=True, null=True)),
                ('lokasi_tip', models.CharField(blank=True, max_length=10, null=True)),
                ('status_tip', models.CharField(blank=True, max_length=30, null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('kode_unit', models.IntegerField(null=True)),
                ('answare_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('is_new_account', models.SmallIntegerField(blank=True, null=True)),
                ('is_blocked', models.SmallIntegerField(blank=True, null=True)),
                ('is_sso', models.SmallIntegerField(blank=True, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'custom_users',
            },
        ),
    ]
