# Generated by Django 4.2.2 on 2023-06-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custom_users',
            table='users_custom',
        ),
    ]
