# Generated by Django 4.2.2 on 2023-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_custom_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custom_users',
            table='users',
        ),
    ]
