# Generated by Django 4.2.2 on 2023-06-13 14:15

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='z_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uname', models.CharField(max_length=255, unique=True)),
                ('upassword', models.CharField(max_length=255)),
                ('isldap', models.SmallIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('work_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('person_id', models.IntegerField(null=True)),
                ('current_loc', models.IntegerField(null=True)),
                ('last_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('ubis_id', models.IntegerField(null=True)),
                ('sub_ubis_id', models.IntegerField(null=True)),
                ('jabatan', models.CharField(blank=True, max_length=200, null=True)),
                ('fixed_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=100, null=True)),
                ('main_role', models.CharField(max_length=11, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.CharField(blank=True, max_length=225, null=True)),
                ('app', models.CharField(blank=True, max_length=20, null=True)),
                ('is_telkom', models.SmallIntegerField(blank=True, null=True)),
                ('employment_category', models.CharField(blank=True, max_length=100, null=True)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('umur', models.IntegerField(null=True)),
                ('masa_bakti', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_id', models.SmallIntegerField(blank=True, null=True)),
                ('pendidikan', models.SmallIntegerField(blank=True, null=True)),
                ('lokasi_tip', models.CharField(blank=True, max_length=10, null=True)),
                ('status_tip', models.CharField(blank=True, max_length=30, null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('kode_unit', models.IntegerField(null=True)),
                ('answare_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('is_new_account', models.SmallIntegerField(blank=True, null=True)),
                ('is_blocked', models.SmallIntegerField(blank=True, null=True)),
                ('is_sso', models.SmallIntegerField(blank=True, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'z_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
