# Generated by Django 4.2.2 on 2023-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_users',
            name='upassword',
            field=models.CharField(db_column='upassword', max_length=255),
        ),
        migrations.RenameField(
            model_name='z_users',
            old_name='upassword',
            new_name='password',
        ),
    ]
