# Generated by Django 4.2.2 on 2023-06-13 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='zpraba_conn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_name', models.CharField(blank=True, max_length=50, null=True)),
                ('conn_params', models.TextField()),
                ('desc', models.CharField(max_length=225)),
                ('is_deactivate', models.SmallIntegerField(blank=True, null=True)),
                ('is_asession', models.SmallIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('adapter', models.CharField(blank=True, max_length=100, null=True)),
                ('ubis_id', models.IntegerField(blank=True, null=True)),
                ('sub_ubis_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_modified', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zpraba_conn',
            },
        ),
    ]
