# Generated by Django 4.2.2 on 2023-06-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpraba_conn',
            name='desc',
            field=models.CharField(default='', max_length=225),
        ),
    ]
