# Generated by Django 4.2.2 on 2023-06-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_custom_users_table'),
        ('datasource', '0003_alter_zpraba_conn_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpraba_conn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to='customuser.custom_users'),
        ),
        migrations.AlterField(
            model_name='zpraba_conn',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_modified', to='customuser.custom_users'),
        ),
        migrations.AlterField(
            model_name='zpraba_conn',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified', to='customuser.custom_users'),
        ),
    ]
